### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by hdrdavies** [koalabears/koala-roar#28]
Would you consider doing this first on Wednesday morning for the project and updating as you go? Might be the easiest way to keep it up to date. 

Also, if someone wants to contribute, they aren't going to know where to start otherwise! 

Also the pics are the wrong way up.

**Comment by hdrdavies** [comment]
http://picresize.com/ 

Is real good for rotating pics!

**Comment by jackcarlisle** [comment]
Thanks, Huw!
