### ISSUE TITLE
t.equal

### ISSUE THREAD

**Issue by claireinez** [koalabears/koala-roar#33]
t.equal takes a third parameter, which is a message. It would be useful for you to generate a message [here](https://github.com/koalabears/koala-roar/blob/master/test/back.js#L20) so that you can see from your tests exactly what is passing/failing (you can get rid of the console.log as well).

**Comment by mk4111** [comment]
Hi Claire :) I think I've fixed them in the said file, and I don't think there are any more in the directory... Hope the messages are acceptable! If they are, we'd love for you to close the issue! Thank you!

**Comment by claireinez** [comment]
Great! You might want to slightly tweak it so that the message includes which url the test is for as well, so that you don't get exactly the same message for each test (and makes it easier to see which test is failing). And you might want to get rid of the console.log on the next line too!
